
FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./
RUN npm install --no-audit --no-fund || true
COPY . .
RUN npx prisma generate && npm run build
EXPOSE 4000
CMD ["npm","start"]
